/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutomationSettings {
  'autoReplyMessage' : string,
  'keyword' : string,
  'automationEnabled' : boolean,
}
export interface CommentReplyLog {
  'status' : boolean,
  'commentSnippet' : string,
  'commentId' : string,
  'user' : Principal,
  'errorDetails' : [] | [string],
  'timestamp' : bigint,
  'replyId' : string,
  'replyMessage' : string,
  'keywordMatched' : string,
}
export interface InstagramCredentials {
  'validated' : boolean,
  'lastValidation' : [] | [bigint],
  'accessToken' : string,
  'igUserId' : string,
  'pageId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'credentials' : [] | [InstagramCredentials],
  'automation' : [] | [AutomationSettings],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllReplyLogs' : ActorMethod<[], Array<CommentReplyLog>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getAutomationSettings' : ActorMethod<[], [] | [AutomationSettings]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCredentials' : ActorMethod<[], [] | [InstagramCredentials]>,
  'getReplyLogs' : ActorMethod<[], Array<CommentReplyLog>>,
  'getReplyStatistics' : ActorMethod<
    [],
    {
      'totalReplies' : bigint,
      'successfulReplies' : bigint,
      'keywordCounts' : Array<[string, bigint]>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAutomationSettings' : ActorMethod<[AutomationSettings], boolean>,
  'validateCredentials' : ActorMethod<[InstagramCredentials], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];