/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommentReplyLog = IDL.Record({
  'status' : IDL.Bool,
  'commentSnippet' : IDL.Text,
  'commentId' : IDL.Text,
  'user' : IDL.Principal,
  'errorDetails' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'replyId' : IDL.Text,
  'replyMessage' : IDL.Text,
  'keywordMatched' : IDL.Text,
});
export const AutomationSettings = IDL.Record({
  'autoReplyMessage' : IDL.Text,
  'keyword' : IDL.Text,
  'automationEnabled' : IDL.Bool,
});
export const InstagramCredentials = IDL.Record({
  'validated' : IDL.Bool,
  'lastValidation' : IDL.Opt(IDL.Int),
  'accessToken' : IDL.Text,
  'igUserId' : IDL.Text,
  'pageId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'credentials' : IDL.Opt(InstagramCredentials),
  'automation' : IDL.Opt(AutomationSettings),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllReplyLogs' : IDL.Func([], [IDL.Vec(CommentReplyLog)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAutomationSettings' : IDL.Func(
      [],
      [IDL.Opt(AutomationSettings)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCredentials' : IDL.Func([], [IDL.Opt(InstagramCredentials)], ['query']),
  'getReplyLogs' : IDL.Func([], [IDL.Vec(CommentReplyLog)], ['query']),
  'getReplyStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalReplies' : IDL.Nat,
          'successfulReplies' : IDL.Nat,
          'keywordCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAutomationSettings' : IDL.Func([AutomationSettings], [IDL.Bool], []),
  'validateCredentials' : IDL.Func([InstagramCredentials], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommentReplyLog = IDL.Record({
    'status' : IDL.Bool,
    'commentSnippet' : IDL.Text,
    'commentId' : IDL.Text,
    'user' : IDL.Principal,
    'errorDetails' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'replyId' : IDL.Text,
    'replyMessage' : IDL.Text,
    'keywordMatched' : IDL.Text,
  });
  const AutomationSettings = IDL.Record({
    'autoReplyMessage' : IDL.Text,
    'keyword' : IDL.Text,
    'automationEnabled' : IDL.Bool,
  });
  const InstagramCredentials = IDL.Record({
    'validated' : IDL.Bool,
    'lastValidation' : IDL.Opt(IDL.Int),
    'accessToken' : IDL.Text,
    'igUserId' : IDL.Text,
    'pageId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'credentials' : IDL.Opt(InstagramCredentials),
    'automation' : IDL.Opt(AutomationSettings),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllReplyLogs' : IDL.Func([], [IDL.Vec(CommentReplyLog)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAutomationSettings' : IDL.Func(
        [],
        [IDL.Opt(AutomationSettings)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCredentials' : IDL.Func([], [IDL.Opt(InstagramCredentials)], ['query']),
    'getReplyLogs' : IDL.Func([], [IDL.Vec(CommentReplyLog)], ['query']),
    'getReplyStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalReplies' : IDL.Nat,
            'successfulReplies' : IDL.Nat,
            'keywordCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAutomationSettings' : IDL.Func([AutomationSettings], [IDL.Bool], []),
    'validateCredentials' : IDL.Func([InstagramCredentials], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };